name: dbt_snowpark_service_now
version: 1.0.0
config-version: 2
profile: dbt_snowpark_service_now

vars:
  INSTANCE: 'https://xxxxx.service-now.com'
  USER: 'admin'
  PASSWORD: 'your_password'

model-paths:
  - models
models:
  dbt_snowpark_service_now:
    +materialized: view
