name: dbt_snowpark_service_now
version: 1.0.0
config-version: 2
profile: dbt_snowpark_service_now

vars:
  SECRET_NAME: 'GSHEETS_SECRETS'
  SPREADSHEET_ID: 'your_spreadsheet_id'
  RANGE_NAME: 'Sheet1'

model-paths:
  - models
models:
  dbt_snowpark_service_now:
    +materialized: view
