dbt_snowpark_service_now:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: XSMALL_WH
      database: SNOWPARK_TESTDB
      schema: PUBLIC
      account: your_account
      user: your_user
